[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault_legacy = "4GcB2GSqc8nHws7eamiYr3LNQgbbrGCEf73xgReN112m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/Gage.Bachik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
